### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Janpaa** [jamesbrooks/poe-horticraft-pricing#2]
Hey I was testing out this app, and ran into following error.

```
 Traceback (most recent call last):
         10: from run.rb:9:in '<main>'
          9: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_pricing.rb:22:in 'run'
          8: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_pricing.rb:29:in 'display_suggested_station_pricing'
          7: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_pricing.rb:29:in 'with_object'
          6: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_pricing.rb:29:in 'each'
          5: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_pricing.rb:30:in 'block in display_suggested_station_pricing'
          4: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_station.rb:10:in 'suggested_pricing_note'
          3: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_station.rb:10:in 'map'
          2: from C:/GitHub/poe-horticraft-pricing/lib/horticrafting_station.rb:10:in 'block in suggested_pricing_note'
          1: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in 'cheapest_price'
 C:/GitHub/poe-horticraft-pricing/lib/craft.rb:17:in 'cheapest_price': unknown currency EX (RuntimeError)
```

**Comment by jamesbrooks** [comment]
Hi @Janpaa - are you running the latest version of the code? This issue popped up earlier but should had been fixed from a release a few hours earlier today.

**Comment by Janpaa** [comment]
Yeah that fixed the problem. Cloned it yesterday and just now tried to use it.
